# Generated by Django 4.0 on 2022-05-31 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.board'),
        ),
    ]
