# Generated by Django 4.0 on 2022-06-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_boards_user_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boards',
            field=models.ManyToManyField(blank=True, to='api.Board'),
        ),
    ]
